export const CONTENT_LOADING='CONTENT_LOADING';
export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const COST_LOW_HIGH ='COST_LOW_HIGH';
export const COST_HIGH_LOW ='COST_High_LOW';
export const GET_LOADED_RESTAURANTS = 'GET_LOADED_RESTAURANTS';
export const HIGH_RATED ='HIGH_RATED';